export const FULL_ROSTER_SUCCESS = "FULL_ROSTER_SUCCESS";
export const FULL_ROSTER_FAIL = "FULL_ROSTER_FAIL";
export const PLAYER_HIGHLIGHT_SUCCESS = "PLAYER_HIGHLIGHT_SUCCESS";
export const PLAYER_HIGHLIGHT_FAIL = "PLAYER_HIGHLIGHT_FAIL";
